version: "3.2"
services:
  # MySQL database shared with tomcat containers.
  db:
    image: mysql:latest
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "example_db"
      MYSQL_USER: "example_db_user"
      MYSQL_PASSWORD: "example_db_pass"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - default

  tomcat:
    # image: tomcat:8.0.44-jre8
    image: tomcat
    # ports:
    #   - "8080:8080"
    environment:
      VIRTUAL_PORT: 8080
      JDBC_URL: "jdbc:mysql://db:3306/example_db?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true&amp;useSSL=false"
      JDBC_USER: "example_db_user"
      JDBC_PASS: "example_db_pass"
    volumes:
      - "./tomcat/webapps:/usr/local/tomcat/webapps"
    networks:
      - default
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx/
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    networks:
      - default
    depends_on:
      - tomcat
  
networks:
  default:

